modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="orderup"
version="0.1.0"
displayName="Order Up!"
authors="Spucio"
description='''
Build and manage a cozy Minecraft restaurant: define a restaurant area, invite a crew,
create menus, serve customers, earn money and restaurant XP, and grow your venue.
'''

[[dependencies.orderup]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.orderup]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.orderup]]
modId="jei"
type="optional"
versionRange="[19.0.0,)"
ordering="NONE"
side="CLIENT"
